version: "0.0.0"

.cargo_all: &cargo_all !inline |-
  set -e
  cargo build --all-features
  cargo test --all
  cargo doc --no-deps

hooks:
  "pre-commit":
    - command: *cargo_all
      files: !glob "**/*.rs"
  "pre-push":
    - command: *cargo_all
      files: !glob "**/*.rs"
