version: "0.0.0"

# Available Git hooks:
# - applypatch-msg 
# - commit-msg 
# - post-applypatch 
# - post-checkout 
# - post-commit 
# - post-merge 
# - post-receive 
# - post-rewrite 
# - post-update 
# - pre-applypatch 
# - pre-auto-gc 
# - pre-commit 
# - pre-push 
# - pre-rebase 
# - pre-receive 
# - prepare-commit-msg 
# - push-to-checkout 
# - sendemail-validate 
# - update

.cargo_fmt_check: &cargo_fmt_check |-
  cargo +nightly fmt --all -- --check
.cargo_test: &cargo_test |-
  cargo test --all

hooks:
  "pre-commit":
    - command: *cargo_fmt_check
    - command: *cargo_test
    - command: 'cargo doc --no-deps'
      severity: warn
  "pre-push":
    - command: *cargo_fmt_check
    - command: *cargo_test

  # "pre-commit":
  #   - program: ["python", "-c"]
  #     severity: warn
  #     command: |-
  #       print('executing hook')
  #       print('calling python program')
