version = "0.0.0"

_shared {
  cargo_all = """set -e
cargo build --all-features
cargo test --all
cargo doc --no-deps"""
}

hooks {
  pre-commit = [
    {
      command.inline = ${_shared.cargo_all}
      files.glob = "**/*.rs"
    }
  ]
  pre-push = [
    {
      command.inline = ${_shared.cargo_all}
      files.glob = "**/*.rs"
    }
  ]
}
