version = "0.0.0"

# Available Git hooks:
# - applypatch-msg 
# - commit-msg 
# - post-applypatch 
# - post-checkout 
# - post-commit 
# - post-merge 
# - post-receive 
# - post-rewrite 
# - post-update 
# - pre-applypatch 
# - pre-auto-gc 
# - pre-commit 
# - pre-push 
# - pre-rebase 
# - pre-receive 
# - prepare-commit-msg 
# - push-to-checkout 
# - sendemail-validate 
# - update

[hooks.pre-commit]
command = "cargo +nightly fmt --all -- --check"

# [hooks.pre-commit]
# program = ["python", "-c"]
# command = """
# print('executing hook')
# print('calling python program')
# """
